module.exports = [
    { title: "Shape of You", artist: "Ed Sheeran" },
    { title: "Someone Like You", artist: "Adele" },
    { title: "Rolling in the Deep", artist: "Adele" },
    { title: "Bohemian Rhapsody", artist: "Queen" },
    { title: "Hotel California", artist: "Eagles" },
    { title: "Billie Jean", artist: "Michael Jackson" },
    { title: "Thinking Out Loud", artist: "Ed Sheeran" },
    { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars" },
    { title: "Closer", artist: "The Chainsmokers ft. Halsey" },
    { title: "Believer", artist: "Imagine Dragons" },
    { title: "Havana", artist: "Camila Cabello ft. Young Thug" },
    { title: "God's Plan", artist: "Drake" },
    { title: "Perfect", artist: "Ed Sheeran" },
    { title: "Blinding Lights", artist: "The Weeknd" },
    { title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
    { title: "Take Me to Church", artist: "Hozier" },
    { title: "Let Her Go", artist: "Passenger" },
    { title: "Photograph", artist: "Ed Sheeran" },
    { title: "Radioactive", artist: "Imagine Dragons" },
    { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee" },
    { title: "Thunder", artist: "Imagine Dragons" },
    { title: "Sugar", artist: "Maroon 5" },
    { title: "Counting Stars", artist: "OneRepublic" },
    { title: "Wake Me Up", artist: "Avicii" },
    { title: "Demons", artist: "Imagine Dragons" },
    { title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra" },
    { title: "Cheap Thrills", artist: "Sia ft. Sean Paul" },
    { title: "Sorry", artist: "Justin Bieber" },
    { title: "Love Yourself", artist: "Justin Bieber" },
    { title: "All of Me", artist: "John Legend" }
];
